<a href="https://colab.research.google.com/github/jawaluke/DL-NLP-natural-language-processing-/blob/master/poetry_creation_LSTM1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# links

!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sonnets.txt \
    -O /tmp/sonnets.txt
data = open('/tmp/sonnets.txt').read()


--2020-08-20 13:39:12--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sonnets.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.204.128, 172.217.203.128, 2607:f8b0:400c:c12::80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.204.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93578 (91K) [text/plain]
Saving to: ‘/tmp/sonnets.txt’

/tmp/sonnets.txt    100%[===================>]  91.38K  --.-KB/s    in 0.002s  

2020-08-20 13:39:12 (50.6 MB/s) - ‘/tmp/sonnets.txt’ saved [93578/93578]



In [2]:
import tensorflow
from tensorflow import keras
from keras.preprocessing.text import Tokenizer

In [3]:
tokenizer = Tokenizer()
data

"FROM fairest creatures we desire increase,\nThat thereby beauty's rose might never die,\nBut as the riper should by time decease,\nHis tender heir might bear his memory:\nBut thou, contracted to thine own bright eyes,\nFeed'st thy light'st flame with self-substantial fuel,\nMaking a famine where abundance lies,\nThyself thy foe, to thy sweet self too cruel.\nThou that art now the world's fresh ornament\nAnd only herald to the gaudy spring,\nWithin thine own bud buriest thy content\nAnd, tender churl, makest waste in niggarding.\nPity the world, or else this glutton be,\nTo eat the world's due, by the grave and thee.\nWhen forty winters shall beseige thy brow,\nAnd dig deep trenches in thy beauty's field,\nThy youth's proud livery, so gazed on now,\nWill be a tatter'd weed, of small worth held:\nThen being ask'd where all thy beauty lies,\nWhere all the treasure of thy lusty days,\nTo say, within thine own deep-sunken eyes,\nWere an all-eating shame and thriftless praise.\nHow much mor

In [4]:
datas = data.lower()
datas = datas.split("\n")

In [5]:
datas

['from fairest creatures we desire increase,',
 "that thereby beauty's rose might never die,",
 'but as the riper should by time decease,',
 'his tender heir might bear his memory:',
 'but thou, contracted to thine own bright eyes,',
 "feed'st thy light'st flame with self-substantial fuel,",
 'making a famine where abundance lies,',
 'thyself thy foe, to thy sweet self too cruel.',
 "thou that art now the world's fresh ornament",
 'and only herald to the gaudy spring,',
 'within thine own bud buriest thy content',
 'and, tender churl, makest waste in niggarding.',
 'pity the world, or else this glutton be,',
 "to eat the world's due, by the grave and thee.",
 'when forty winters shall beseige thy brow,',
 "and dig deep trenches in thy beauty's field,",
 "thy youth's proud livery, so gazed on now,",
 "will be a tatter'd weed, of small worth held:",
 "then being ask'd where all thy beauty lies,",
 'where all the treasure of thy lusty days,',
 'to say, within thine own deep-sunken eyes,',

In [6]:
from keras.preprocessing.sequence import pad_sequences

tokenizer.fit_on_texts(datas)
word_index = tokenizer.word_index

In [7]:
word_index

{'and': 1,
 'the': 2,
 'to': 3,
 'of': 4,
 'my': 5,
 'i': 6,
 'in': 7,
 'that': 8,
 'thy': 9,
 'thou': 10,
 'with': 11,
 'for': 12,
 'is': 13,
 'love': 14,
 'not': 15,
 'but': 16,
 'a': 17,
 'me': 18,
 'thee': 19,
 'so': 20,
 'be': 21,
 'as': 22,
 'all': 23,
 'you': 24,
 'his': 25,
 'which': 26,
 'when': 27,
 'it': 28,
 'this': 29,
 'by': 30,
 'your': 31,
 'doth': 32,
 'do': 33,
 'from': 34,
 'on': 35,
 'or': 36,
 'no': 37,
 'then': 38,
 'have': 39,
 'what': 40,
 'are': 41,
 'if': 42,
 'more': 43,
 'mine': 44,
 'their': 45,
 'shall': 46,
 'sweet': 47,
 'time': 48,
 'will': 49,
 'they': 50,
 'beauty': 51,
 'nor': 52,
 'eyes': 53,
 'art': 54,
 'her': 55,
 'heart': 56,
 'yet': 57,
 'o': 58,
 'than': 59,
 'can': 60,
 'should': 61,
 'thine': 62,
 'now': 63,
 'where': 64,
 'make': 65,
 'one': 66,
 'hath': 67,
 'he': 68,
 'fair': 69,
 'still': 70,
 'how': 71,
 'eye': 72,
 'him': 73,
 'like': 74,
 'true': 75,
 'see': 76,
 'am': 77,
 'she': 78,
 'those': 79,
 'though': 80,
 'being': 81,
 'some'

In [8]:
total_words = len(word_index)+1
total_words

3211

In [9]:
input_sequence = []

for i in datas:
  token_list = tokenizer.texts_to_sequences([i])[0]
  print(token_list)
  for i in range(1,len(token_list)):
    print(i)
    n_gram_seq = token_list[:i+1]
    print(n_gram_seq)
  break

[34, 417, 877, 166, 213, 517]
1
[34, 417]
2
[34, 417, 877]
3
[34, 417, 877, 166]
4
[34, 417, 877, 166, 213]
5
[34, 417, 877, 166, 213, 517]


In [10]:
input_sequence = []

for i in datas:
  token_list = tokenizer.texts_to_sequences([i])[0]

  for i in range(1,len(token_list)):
    
    n_gram_seq = token_list[:i+1]
    input_sequence.append(n_gram_seq)

In [11]:
input_sequence

[[34, 417],
 [34, 417, 877],
 [34, 417, 877, 166],
 [34, 417, 877, 166, 213],
 [34, 417, 877, 166, 213, 517],
 [8, 878],
 [8, 878, 134],
 [8, 878, 134, 351],
 [8, 878, 134, 351, 102],
 [8, 878, 134, 351, 102, 156],
 [8, 878, 134, 351, 102, 156, 199],
 [16, 22],
 [16, 22, 2],
 [16, 22, 2, 879],
 [16, 22, 2, 879, 61],
 [16, 22, 2, 879, 61, 30],
 [16, 22, 2, 879, 61, 30, 48],
 [16, 22, 2, 879, 61, 30, 48, 634],
 [25, 311],
 [25, 311, 635],
 [25, 311, 635, 102],
 [25, 311, 635, 102, 200],
 [25, 311, 635, 102, 200, 25],
 [25, 311, 635, 102, 200, 25, 278],
 [16, 10],
 [16, 10, 880],
 [16, 10, 880, 3],
 [16, 10, 880, 3, 62],
 [16, 10, 880, 3, 62, 85],
 [16, 10, 880, 3, 62, 85, 214],
 [16, 10, 880, 3, 62, 85, 214, 53],
 [1372, 9],
 [1372, 9, 1373],
 [1372, 9, 1373, 636],
 [1372, 9, 1373, 636, 11],
 [1372, 9, 1373, 636, 11, 122],
 [1372, 9, 1373, 636, 11, 122, 1374],
 [1372, 9, 1373, 636, 11, 122, 1374, 1375],
 [201, 17],
 [201, 17, 1376],
 [201, 17, 1376, 64],
 [201, 17, 1376, 64, 518],
 [201,

In [12]:
# getting the maximum valuer from the passage

max_seq_len = max([len(x) for x in input_sequence])
max_seq_len

11

In [13]:
# sequence padding
import numpy as np
input_sequences = np.array(pad_sequences(input_sequence, maxlen = max_seq_len, padding = "pre"))
input_sequences

array([[   0,    0,    0, ...,    0,   34,  417],
       [   0,    0,    0, ...,   34,  417,  877],
       [   0,    0,    0, ...,  417,  877,  166],
       ...,
       [   0,    0,    0, ...,  493,  493, 3210],
       [   0,    0,    0, ...,  493, 3210,   15],
       [   0,    0,    0, ..., 3210,   15,   14]], dtype=int32)

In [14]:
# splitiing the x and y labels
X = input_sequences[:,:-1]
print(X)
y = input_sequences[:,-1]
print(y)

[[   0    0    0 ...    0    0   34]
 [   0    0    0 ...    0   34  417]
 [   0    0    0 ...   34  417  877]
 ...
 [   0    0    0 ... 3209  493  493]
 [   0    0    0 ...  493  493 3210]
 [   0    0    0 ...  493 3210   15]]
[ 417  877  166 ... 3210   15   14]


In [15]:
# label for y

y = keras.utils.to_categorical(y)
print(y)
len(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


15462

In [16]:
# model.define

model = keras.Sequential([
keras.layers.Embedding(total_words, 64, input_length= max_seq_len-1),
keras.layers.Bidirectional(keras.layers.LSTM(20)),
keras.layers.Dense(total_words, activation= "softmax")                          
        ])


In [17]:
model.compile(
    optimizer = "adam",
    loss = "categorical_crossentropy",
    metrics = ["accuracy"]
)

In [18]:
history = model.fit(X,y , epochs = 100, verbose = 2)

Epoch 1/100
484/484 - 6s - loss: 6.9239 - accuracy: 0.0215
Epoch 2/100
484/484 - 6s - loss: 6.5053 - accuracy: 0.0222
Epoch 3/100
484/484 - 6s - loss: 6.4195 - accuracy: 0.0277
Epoch 4/100
484/484 - 6s - loss: 6.3430 - accuracy: 0.0345
Epoch 5/100
484/484 - 6s - loss: 6.2697 - accuracy: 0.0369
Epoch 6/100
484/484 - 6s - loss: 6.1934 - accuracy: 0.0396
Epoch 7/100
484/484 - 6s - loss: 6.1178 - accuracy: 0.0430
Epoch 8/100
484/484 - 6s - loss: 6.0410 - accuracy: 0.0455
Epoch 9/100
484/484 - 6s - loss: 5.9629 - accuracy: 0.0459
Epoch 10/100
484/484 - 6s - loss: 5.8806 - accuracy: 0.0520
Epoch 11/100
484/484 - 6s - loss: 5.7956 - accuracy: 0.0540
Epoch 12/100
484/484 - 6s - loss: 5.7142 - accuracy: 0.0605
Epoch 13/100
484/484 - 6s - loss: 5.6346 - accuracy: 0.0624
Epoch 14/100
484/484 - 6s - loss: 5.5494 - accuracy: 0.0666
Epoch 15/100
484/484 - 6s - loss: 5.4656 - accuracy: 0.0709
Epoch 16/100
484/484 - 5s - loss: 5.3853 - accuracy: 0.0746
Epoch 17/100
484/484 - 6s - loss: 5.2967 - accura

In [20]:
# prediction words results

text_to_pred = "jenifier you're my only hope"
next_word = 20

for i in range(next_word):
  token_list = tokenizer.texts_to_sequences([text_to_pred])[0]
  print(token_list)

  token_lists = pad_sequences([token_list], maxlen= max_seq_len-1, padding="pre")
  print(token_lists)

[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]
[[  0   0   0   0   0   0   0   5 352 393]]
[5, 352, 393]


In [27]:
text_to_pred = "jenifier where she is alone"
next_word = 100

for i in range(next_word):
  token_list = tokenizer.texts_to_sequences([text_to_pred])[0]
  
  token_lists = pad_sequences([token_list], maxlen= max_seq_len-1, padding="pre")
  predicted = model.predict_classes(token_lists, verbose = 0)
  
  output = ""
  for words, index in tokenizer.word_index.items():
    if index == predicted:
      output = words
      break
  text_to_pred +=" "+ output
# combine the result with output words

print(text_to_pred)



jenifier where she is alone thou art as rigor her transferr'd ' had days foolish pride ' ' ' with me tears thou leave quite canst grew lies dost ' bettering lies you dead kind days 'will' ' of wrongs 'will' in giving ' have often ' thereof days 'will' spread quite a tomb me express'd tell ' so blind dost done be thine seeing me now be thine own true skill respect 'will ' days wherein doth special lest corrupt to complain or canopy the kings of me pride express'd sky of brow tell ' ' foot doing doing me stol'n thine annoy thine
